06/diplomat/config/routes.rb
Diplomat::Application.routes.draw do
  resources :authors

  get "home/index"

  root 'home#index'

end

06/diplomat/app/models/author.rb
class Author < ActiveRecord::Base
	validates :firstname, presence: true
	validates :surname, presence: true
end

06/diplomat/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

06/diplomat/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render action: 'show', status: :created, location: @author }
      else
        format.html { render action: 'new' }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:firstname, :surname, :title_before, :title_after)
    end
end

06/diplomat/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

06/diplomat/app/helpers/application_helper.rb
module ApplicationHelper
end

06/diplomat/app/helpers/authors_helper.rb
module AuthorsHelper
end

06/diplomat/app/helpers/home_helper.rb
module HomeHelper
end

06/diplomat/app/views/authors/_form.html.haml
= form_for @author do |f|
  - if @author.errors.any?
    #error_explanation
      %h2= "#{pluralize(@author.errors.count, "error")} prohibited this author from being saved:"
      %ul
        - @author.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :firstname
    = f.text_field :firstname
  .field
    = f.label :surname
    = f.text_field :surname
  .field
    = f.label :title_before
    = f.text_field :title_before
  .field
    = f.label :title_after
    = f.text_field :title_after
  .actions
    = f.submit 'Save'

06/diplomat/app/views/authors/edit.html.haml
%h1 Editing author

= render 'form'

= link_to 'Show', @author
\|
= link_to 'Back', authors_path

06/diplomat/app/views/authors/index.html.haml
%h1 Listing authors

%table
  %tr
    %th Firstname
    %th Surname
    %th Title before
    %th Title after
    %th
    %th
    %th

  - @authors.each do |author|
    %tr
      %td= author.firstname
      %td= author.surname
      %td= author.title_before
      %td= author.title_after
      %td= link_to 'Show', author
      %td= link_to 'Edit', edit_author_path(author)
      %td= link_to 'Destroy', author, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Author', new_author_path

06/diplomat/app/views/authors/new.html.haml
%h1 New author

= render 'form'

= link_to 'Back', authors_path

06/diplomat/app/views/authors/show.html.haml
%p#notice= notice

%p
  %b Firstname:
  = @author.firstname
%p
  %b Surname:
  = @author.surname
%p
  %b Title before:
  = @author.title_before
%p
  %b Title after:
  = @author.title_after

= link_to 'Edit', edit_author_path(@author)
\|
= link_to 'Back', authors_path

06/diplomat/app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.haml

06/diplomat/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Diplomat</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>